#!/usr/bin/env sh

if [ -L $0 ]; then
  src=`which chippy_genome`
  src=`readlink $src`
else
  src=$0
fi

script_dir=`dirname $src`
chippy_path=`dirname $script_dir`
export PYTHONPATH=$PYTHONPATH:$chippy_path

python $chippy_path/chippy/ref/genome.py $@
